### ISSUE TITLE
WG: Proposal for CNCF Accessibility (A11y) WG

### ISSUE THREAD

**Issue by karayim** [cncf/tag-observability#164]
## Tasks
[Charter Proposal](https://docs.google.com/document/d/1NvmZuCYKedifvMlm49-AM2nILno-ZZLFhN1jPRM6v90/edit?usp=sharing)
- [ ] call for contributions
- [ ] community feedback
- [ ] present to TAG
- [ ] TOC vote
- [ ] email TAG Observability list
- [ ] figure out the [new process](https://github.com/cncf/toc/issues/1158) at the TOC level

**Comment by alolita** [comment]
@karayim can you join in for tomorrow's O11y TAG (Feb 6) meeting to walkthrough your proposal and discuss!

**Comment by alolita** [comment]
Hi @karayim are you available to join in for one of the June TAG meetings to give us an update from the a11y workgroup?

**Comment by alolita** [comment]
Closing this issue since there is no response from the initial proposer for this workgroup. Let's reopen when there is active interest.
