### ISSUE TITLE
Form Program: Annual Sandbox Review

### ISSUE THREAD

**Issue by halcyondude** [cncf/tag-observability#80]
# Annual Review for Sandbox projects

## Context

- https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md
- all reviews: https://github.com/cncf/toc/tree/main/reviews

## Tasks

- [ ] Create Program to facilitate reporting/tracking reports, and making them easy to find.
- [ ] Establish tooling/process such that
    - [ ] self-serve semantics are employed. All data --> GitHub, managed via PR.
    - [ ] outcome is a tool useful for all TAG's (not just Observability). This could include issue templates, timeline representation
    - [ ] all  meta-data needs to reside in GitHub as JSON (preferred) or CSV.  GitHub Flat actions can help here, as does flatgithub://. This also allows reconstruction later, or pulling actual documents into graph.cncf.io (w/ Lucene full-text indexing)
- [ ] Solicit feedback from TOC and @amye. 

## Outcome

- [ ] Automated, useful reports are in place and discoverable. 
- [ ] Coordinate with the [Landscape Graph project (graph.cncf.io)](https://github.com/cncf/landscape-graph)
- [ ] Present to #tag-chairs, #tag-contributor-strategy, #toc with learnings and proposal for all TAG's.
    - [ ] Webinar describing the process, how to engage, and why one would.
    - [ ] Pitch Deck (1, 1-2, or 1-3 slides --> understanding)

**Comment by dominick-blue** [comment]
Commenting here for an assignment!

**Comment by dominick-blue** [comment]
Would like feedback on the initial presentation, [here](https://docs.google.com/presentation/d/1Ap2zGL7JFUCXta2Z1WWXYNMeoX_3chUeMgsaKuIn_3c/edit?usp=sharing).

**Comment by halcyondude** [comment]
this stalled due to resourcing, but remains a good start for some of what the TOC is working on now.  @amye FYI
